# Export named symbols from Ghidra to binanana .sym format.
#
# Usage (GUI): Run from Script Manager, prompts for output file path.
# Usage (headless): -postScript export_symbols.py "/path/to/output.sym"
#
# Exports all user-named functions and data labels, skipping
# auto-generated names (FUN_, DAT_, LAB_, etc.) and external/thunk
# functions.
#
# Output format (64-bit addresses):
#   FunctionName 00000001400AD020 f end=00000001400AD0A3
#   DataLabel    0000000142B60E20 l
#
# @category binanana

from ghidra.program.model.symbol import SourceType

functionManager = currentProgram.getFunctionManager()
symbolTable = currentProgram.getSymbolTable()
listing = currentProgram.getListing()

# Support both GUI (askFile) and headless (getScriptArgs) modes
args = getScriptArgs()
if args:
    import java.io.File
    file_location = java.io.File(args[0])
else:
    file_location = askFile("Choose output file", "Export")

AUTO_PREFIXES = ("FUN_", "DAT_", "LAB_", "PTR_", "s_", "u_", "switch",
                 "caseD_", "CASE_", "thunk_FUN_")


def is_auto_name(name):
    """Check if a symbol name was auto-generated by Ghidra."""
    for prefix in AUTO_PREFIXES:
        if name.startswith(prefix):
            return True
    return False


def export_function_symbols(f_out):
    """Export all user-named functions."""
    count = 0
    for func in functionManager.getFunctionsNoStubs(True):
        monitor.checkCanceled()

        if func.isExternal() or func.isThunk():
            continue

        name = func.getName()
        if is_auto_name(name):
            continue

        start = func.getBody().getMinAddress().getOffset()
        end = func.getBody().getMaxAddress().getOffset() + 1

        f_out.write("{name} {start:016X} f end={end:016X}\n".format(
            name=name, start=start, end=end))
        count += 1

    return count


def export_data_labels(f_out):
    """Export all user-named data labels."""
    count = 0
    for symbol in symbolTable.getAllSymbols(True):
        monitor.checkCanceled()

        if symbol.isExternal():
            continue
        if symbol.getSource() == SourceType.DEFAULT:
            continue

        name = symbol.getName()
        if is_auto_name(name):
            continue

        # Skip functions (already exported above)
        if functionManager.getFunctionAt(symbol.getAddress()) is not None:
            continue

        addr = symbol.getAddress().getOffset()
        f_out.write("{name} {addr:016X} l\n".format(name=name, addr=addr))
        count += 1

    return count


if hasattr(file_location, 'absolutePath'):
    output_path = str(file_location.absolutePath)
else:
    output_path = str(file_location)
with open(output_path, "w") as f_out:
    func_count = export_function_symbols(f_out)
    label_count = export_data_labels(f_out)
    print("Exported {} functions and {} data labels".format(
        func_count, label_count))
